# Numpy Shapes 

## 1. Create the following Numpy array of 32-bit integers

        array([[1, 1, 1, 1, 1], 
               [0, 1, 1, 1, 1],
               [0, 0, 1, 1, 1],
               [0, 0, 0, 1, 1],
               [0, 0, 0, 0, 1]])

In [1]:
import numpy as np
from numpy import array

In [2]:
arr=1*np.fromfunction(lambda i, j : j>=i, (5,5), dtype=np.int32)

In [3]:
print(arr)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


## 2. Create the following Numpy array of 16-bit integers

        array([[ 1,  2,  3,  4,  5],
               [ 0,  6,  7,  8,  9],
               [ 0,  0, 10, 11, 12],
               [ 0,  0,  0, 13, 14],
               [ 0,  0,  0,  0, 15]])

In [4]:
arr=1*np.fromfunction(lambda i, j : j>=i, (5,5), dtype=np.int32)
counter=1
for i in range(len(arr)):
    for j in range(len(arr[0])):
        if j>=i:
            arr[i][j]=counter
            counter+=1

In [5]:
print(arr)

[[ 1  2  3  4  5]
 [ 0  6  7  8  9]
 [ 0  0 10 11 12]
 [ 0  0  0 13 14]
 [ 0  0  0  0 15]]


## 3.
    Given the following two-dimensional array, set the diagonal element to the average of the columns in each respective row not counting the diagonal element in each row. Note that the diagonal element itself is not part of the calculation. It is just a placeholder for the result.

        [[0,   3, 14, 13, 12],
         [13,  0,  8,  5, 11],
         [11, 11,  0, 12, 10],
         [11, 12,  1,  0, 10],
         [13, 12, 11,  4,  0]]

    In this case, your answer should look like the following

        [[ 10.5 ,   3.  ,  14.  ,  13.  ,  12.  ],
         [ 13.  ,   9.25,   8.  ,   5.  ,  11.  ],
         [ 11.  ,  11.  ,  11.  ,  12.  ,  10.  ],
         [ 11.  ,  12.  ,   1.  ,   8.5 ,  10.  ],
         [ 13.  ,  12.  ,  11.  ,   4.  ,  10.  ]]

    In the general case, the diagonal elements won't necessarily be equal to zero like they are here!

In [6]:
from __future__ import division
import numpy as np
from numpy import float
def average_into_diagonal(x):
    assert isinstance(x,np.ndarray),'input is not a array type'
    assert x.ndim == 2,'input matrix is not a 2D matrix'
    assert x.shape[0] == x.shape[1],'input matrix is not a square shape'
    x = x.astype(float)
    n = len(x)  
    for i in range(n): 
        sum_of_row = 0
        for j in range(n):
            if i == j:
                pass
            else:
                sum_of_row += x[i][j]
            x[i][i] = sum_of_row/(n-1)
    return x

In [7]:
x = [[0,   3, 14, 13, 12],
 [13,  0,  8,  5, 11],
 [11, 11,  0, 12, 10],
 [11, 12,  1,  0, 10],
 [13, 12, 11,  4,  0]]

x = np.asarray(x)
newX = average_into_diagonal(x)
print(newX)

[[10.5   3.   14.   13.   12.  ]
 [13.    9.25  8.    5.   11.  ]
 [11.   11.   11.   12.   10.  ]
 [11.   12.    1.    8.5  10.  ]
 [13.   12.   11.    4.   10.  ]]
